exclude: '(^|/)(?:node_modules|dist)(?:/|$)|package-lock\.json|.*\.(?:md|min\.js|yaml)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # - id: check-yaml
      # - id: check-added-large-files

  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.6.1"
    hooks:
      - id: biome-check
        name: "🟨 javascript · Lint, format, and safe fixes with Biome"
        entry: biome format --write
        language: node
        additional_dependencies:
          - "@biomejs/biome@1.9.4"
        files: \.js$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: "✨ misc-files · Format misc web files"
        types_or: [css, json, vue]
        additional_dependencies:
          - prettier@3.4.2